# Generated by Django 6.0.2 on 2026-02-23 04:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(choices=[('HAIRCUT', 'Haircut'), ('FACIAL', 'Facial'), ('MANICURE', 'Manicure'), ('PEDICURE', 'Pedicure')], max_length=20)),
                ('stylist_name', models.CharField(max_length=100)),
                ('appointment_datetime', models.DateTimeField()),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('BOOKED', 'Booked'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed')], default='BOOKED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['appointment_datetime'],
                'constraints': [models.UniqueConstraint(fields=('stylist_name', 'appointment_datetime'), name='unique_stylist_appointment_slot')],
            },
        ),
    ]
